/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      listStyleType: { none: "disc", disc: "disc", decimal: "decimal" },
      colors: {
        /* shadcn bridge */
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },

        /* ── Glass Stage system ── */
        stage: "var(--stage)",
        "stage-hi": "var(--stage-hi)",
        "stage-lo": "var(--stage-lo)",
        glass: "var(--glass)",
        "glass-lite": "var(--glass-lite)",
        "glass-bright": "var(--glass-bright)",
        "glass-deep": "var(--glass-deep)",
        plate: "var(--plate)",
        ink: "var(--ink)",
        "ink-soft": "var(--ink-soft)",
        "muted-ink": "var(--muted-ink)",
        hairline: "var(--hairline)",
        "hairline-2": "var(--hairline-2)",
        acc: "var(--acc)",
        "acc-hi": "var(--acc-hi)",
        "acc-text": "var(--acc-text)",
        "acc-wash": "var(--acc-wash)",
        "on-acc": "var(--on-acc)",

        /* ── Legacy aliases — admin / manage / ui, out of redesign scope ── */
        canvas: "var(--canvas)",
        tile: "var(--tile)",
        "tile-2": "var(--tile-2)",
        paper: "var(--paper)",
        "paper-2": "var(--paper-2)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        "hairline-strong": "var(--hairline-strong)",
        brand: "var(--brand)",
        "brand-bright": "var(--brand-bright)",
        gold: "var(--gold)",
        ash: "#f0f1f3",
        navy: "#1c3454",
        sky: "#74c0fc",
        ocean: "#3e6392",
        grass: "#63e6be",
        cheese: "#ffd43b",
        orange: "#ef8114",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        xs: "var(--r-xs)",
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        tile: "var(--r-md)",
        panel: "var(--r-lg)",
        bay: "var(--r-xl)",
      },
      backdropBlur: { xs: "6px", glass: "16px", "glass-lg": "28px" },
      boxShadow: {
        e1: "var(--sh-1)",
        e2: "var(--sh-2)",
        e3: "var(--sh-3)",
        lift: "var(--sh-lift)",
        acc: "var(--sh-acc)",
        edge: "var(--edge)",
        /* legacy */
        paper: "rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px",
        soft: "var(--sh-1)",
        float: "var(--sh-2)",
      },
      transitionTimingFunction: {
        premium: "cubic-bezier(0.32, 0.72, 0, 1)",
        smooth: "cubic-bezier(0.22, 1, 0.36, 1)",
        glass: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      keyframes: {
        "accordion-down": { from: { height: 0 }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: 0 } },
      },
      animation: { "accordion-down": "accordion-down 0.2s ease-out", "accordion-up": "accordion-up 0.2s ease-out" },
      backgroundColor: { ash: "#f0f1f3", navy: "#1c3454", sky: "#74c0fc", ocean: "#3e6392", grass: "#63e6be", cheese: "#ffd43b", orange: "#ef8114" },
      textColor: { ash: "#f0f1f3", navy: "#1c3454", sky: "#74c0fc", ocean: "#3e6392", grass: "#63e6be", cheese: "#ffd43b", orange: "#ef8114" },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
